version: '2'
services:
  front:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    links:
      - mysql:mysql
      - memcached:memcached
    volumes:
      - ./www:/var/www
      - ./sites:/etc/nginx/conf.d
      - ./logs:/var/log/supervisor

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes_from:
      - mysqlData
    environment:
      MYSQL_ROOT_PASSWORD: password

  mysqlData:
    image: mysql
    entrypoint: /bin/bash

  memcached:
    image: memcached
    ports:
      - "11211:11211"
